services:
  backend:
    image: vishwasgowdahv/trimmy-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: trimmy-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    restart: unless-stopped

  frontend:
    image: vishwasgowdahv/trimmy-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: trimmy-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped
